# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-12-10 11:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_sticky'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(default='k_s', editable=False, max_length=3),
        ),
    ]
